sudo: false
before_script:
  - composer self
  - composer --version
  - composer install -n
language: php
php:
  - 7
script:
  - phpunit --coverage-text --coverage-clover=coverage.clover
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
