sudo: false
before_script:
  - composer self
  - composer --version
  - composer install -n
language: php
php:
  - 7.0
  - 7.1
  - 7.2
  - hhvm
script:
  - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
